import type { Metadata } from "next";
import Head from "next/head";
import { Playfair_Display, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import "./app.css";
import Navbar from "./Navbar";
import Footer from "./Footer";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["600"],
  variable: "--font-playfair",
});
const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Shoresh Group",
  description: "Generated by shoresh Group",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
        ></link>
      </head>

      <body className={`${playfair.variable} ${sourceSans.variable}`}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
