import type { Metadata } from "next";
import { Playfair_Display, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "900"],
});
const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  weight: ["200", "400", "900"],
});

export const metadata: Metadata = {
  title: "Shoresh Group",
  description: "Generated by shoresh Group",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sourceSans.className}>
        <Navbar />
        <main className="container mx-auto">{children}</main>
      </body>
    </html>
  );
}
